version: '3.7'

services:
  postgres:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER: person
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dataz
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  edgedb:
    image: edgedb/edgedb:1-beta3
    environment:
      EDGEDB_POSTGRES_DSN: postgres://person:password@postgres:5432/dataz
      EDGEDB_PASSWORD: password
      EDGEDB_GENERATE_SELF_SIGNED_CERT: 1
    depends_on:
      - postgres
    ports:
      - '5656:5656'
